### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by knownasnaffy** [knownasnaffy/anDiary#57]
Priority
- [x] - Use [Tauri](https://tauri.app/) for creating an app

Chore:
- [ ] Make a single eslint config in the root dir

Front End:
- [ ] Command Platelet for app
- [ ] App intro page
- [ ] Login forms

**Comment by naffydharni006** [comment]
# Components

**Button:**
- [ ] - Primary
- [ ] - Error
- [ ] - Success
- [ ] - Icon

**Input:**
- [ ] - Main
- [ ] - Name
- [ ] - Password
- [ ] - Browse File

**Avatar:**
- [ ] - Main
